/**
 * Dữ liệu mẫu khớp với prisma/seed.ts — dùng khi chưa kết nối API
 * (xem lib/api.ts: tự fallback về dữ liệu này nếu API không chạy).
 * Giá trị thể hiện đúng góc nhìn KHÁCH VÃNG LAI: sản phẩm ẩn giá có
 * priceOnRequest=true và không có bảng giá bậc.
 */
import type { Category, Post, Product, Review } from './types';

export const MOCK_PRODUCTS: Product[] = [
  {
    id: 'p-xoai-tron',
    name: 'Xoài tròn Yên Châu',
    slug: 'xoai-tron-yen-chau',
    categorySlug: 'xoai',
    categoryName: 'Xoài',
    unit: 'kg',
    minOrderQuantity: 10,
    shortDescription:
      'Xoài tròn bản địa thơm đậm, vỏ xanh thịt vàng, được bảo hộ chỉ dẫn địa lý Yên Châu.',
    description:
      'Xoài tròn Yên Châu là giống bản địa được bảo hộ chỉ dẫn địa lý, quả nhỏ 200–300g, vỏ xanh, thịt vàng óng, ngọt đậm và thơm đặc trưng không lẫn với bất kỳ giống xoài nào khác. Vườn đạt chuẩn VietGAP, có mã số vùng trồng phục vụ xuất khẩu chính ngạch.\n\nQuy cách: thùng giấy 10kg hoặc sọt nhựa 20kg; hỗ trợ đóng hàng xuất khẩu theo yêu cầu.',
    origin: 'Giống bản địa Yên Châu (chỉ dẫn địa lý)',
    growingRegion: 'Yên Châu, Sơn La',
    harvestPeriod: 'Tháng 5 – 8',
    season: { startMonth: 5, endMonth: 8, peakMonth: 6, label: 'Tháng 5 – 8' },
    certifications: ['VietGAP'],
    isExportQuality: true,
    isFeatured: true,
    retailPrice: 35000,
    priceOnRequest: false,
    priceTiers: [
      { minQuantity: 10, price: 35000, label: 'Từ 10kg' },
      { minQuantity: 50, price: 32000, label: 'Từ 50kg' },
      { minQuantity: 100, price: 30000, label: 'Từ 100kg' },
      { minQuantity: 500, price: 27000, label: 'Từ 500kg' },
      { minQuantity: 1000, price: 25000, label: 'Từ 1 tấn' },
    ],
    emoji: '🥭',
    gradient: 'from-amber-200 to-yellow-100',
  },
  {
    id: 'p-xoai-tuong',
    name: 'Xoài tượng da xanh',
    slug: 'xoai-tuong-da-xanh',
    categorySlug: 'xoai',
    categoryName: 'Xoài',
    unit: 'kg',
    minOrderQuantity: 10,
    shortDescription: 'Quả to 0,8–1,2kg, ít xơ, chuyên hàng xuất khẩu Trung Quốc và chế biến.',
    description:
      'Xoài tượng da xanh trồng theo tiêu chuẩn GlobalGAP, quả to đều, ít xơ, vị ngọt thanh, chịu vận chuyển tốt — lựa chọn hàng đầu cho đơn container xuất khẩu và chuỗi chế biến.',
    origin: 'Giống Đài Loan ghép',
    growingRegion: 'Yên Châu, Sơn La',
    harvestPeriod: 'Tháng 5 – 9',
    season: { startMonth: 5, endMonth: 9, peakMonth: 7, label: 'Tháng 5 – 9' },
    certifications: ['GlobalGAP'],
    isExportQuality: true,
    isFeatured: false,
    retailPrice: 28000,
    priceOnRequest: false,
    priceTiers: [
      { minQuantity: 10, price: 28000, label: 'Từ 10kg' },
      { minQuantity: 100, price: 24000, label: 'Từ 100kg' },
      { minQuantity: 500, price: 21000, label: 'Từ 500kg' },
      { minQuantity: 1000, price: 19000, label: 'Từ 1 tấn' },
    ],
    emoji: '🥭',
    gradient: 'from-green-200 to-lime-100',
  },
  {
    id: 'p-nhan',
    name: 'Nhãn Sông Mã',
    slug: 'nhan-song-ma',
    categorySlug: 'nhan',
    categoryName: 'Nhãn',
    unit: 'kg',
    minOrderQuantity: 10,
    shortDescription: 'Cùi dày, hạt nhỏ, ngọt sắc — vùng trồng có mã số xuất khẩu chính ngạch.',
    description:
      'Nhãn Sông Mã từ thủ phủ nhãn miền Bắc với hơn 7.500ha. Cùi dày giòn, hạt nhỏ, độ ngọt cao và đồng đều. Vùng trồng được cấp mã số xuất khẩu, đáp ứng kiểm dịch thực vật cho thị trường Trung Quốc, EU.',
    origin: 'Nhãn miền thiết ghép cải tạo',
    growingRegion: 'Sông Mã, Sơn La',
    harvestPeriod: 'Tháng 7 – 9',
    season: { startMonth: 7, endMonth: 9, peakMonth: 8, label: 'Tháng 7 – 9' },
    certifications: ['VietGAP'],
    isExportQuality: true,
    isFeatured: true,
    retailPrice: 40000,
    priceOnRequest: false,
    priceTiers: [
      { minQuantity: 10, price: 40000, label: 'Từ 10kg' },
      { minQuantity: 50, price: 36000, label: 'Từ 50kg' },
      { minQuantity: 100, price: 33000, label: 'Từ 100kg' },
      { minQuantity: 500, price: 30000, label: 'Từ 500kg' },
      { minQuantity: 1000, price: 27000, label: 'Từ 1 tấn' },
    ],
    emoji: '🟤',
    gradient: 'from-orange-200 to-amber-100',
  },
  {
    id: 'p-man',
    name: 'Mận hậu Mộc Châu',
    slug: 'man-hau-moc-chau',
    categorySlug: 'man',
    categoryName: 'Mận',
    unit: 'kg',
    minOrderQuantity: 10,
    shortDescription: 'Mận hậu trái to giòn ngọt, hàng tuyển size 18–22 quả/kg.',
    description:
      'Mận hậu trồng trên cao nguyên Mộc Châu 1.050m, biên độ nhiệt ngày đêm lớn cho quả giòn, ngọt thanh xen chua nhẹ. Hàng tuyển chọn size đều, chịu được vận chuyển xa.',
    origin: 'Mận hậu cao nguyên',
    growingRegion: 'Mộc Châu, Sơn La',
    harvestPeriod: 'Tháng 5 – 7',
    season: { startMonth: 5, endMonth: 7, peakMonth: 6, label: 'Tháng 5 – 7' },
    certifications: ['VietGAP'],
    isExportQuality: false,
    isFeatured: true,
    retailPrice: 45000,
    priceOnRequest: false,
    priceTiers: [
      { minQuantity: 10, price: 45000, label: 'Từ 10kg' },
      { minQuantity: 50, price: 40000, label: 'Từ 50kg' },
      { minQuantity: 100, price: 36000, label: 'Từ 100kg' },
      { minQuantity: 500, price: 32000, label: 'Từ 500kg' },
    ],
    emoji: '🍑',
    gradient: 'from-rose-200 to-red-100',
  },
  {
    id: 'p-dau-tay',
    name: 'Dâu tây Hana Mộc Châu',
    slug: 'dau-tay-hana-moc-chau',
    categorySlug: 'dau-tay',
    categoryName: 'Dâu tây',
    unit: 'kg',
    minOrderQuantity: 5,
    shortDescription: 'Dâu Hana trồng nhà màng hữu cơ, hái buổi sớm giao trong ngày.',
    description:
      'Dâu tây giống Hana Nhật Bản trồng nhà màng theo hướng hữu cơ. Hái lúc sáng sớm, đóng hộp xốp lạnh giao trong ngày cho chuỗi cửa hàng và nhà hàng. Giá biến động theo ngày — vui lòng yêu cầu báo giá.',
    origin: 'Giống Hana Nhật Bản',
    growingRegion: 'Mộc Châu, Sơn La',
    harvestPeriod: 'Tháng 12 – 4',
    season: { startMonth: 12, endMonth: 4, peakMonth: 2, label: 'Tháng 12 – 4' },
    certifications: ['Organic'],
    isExportQuality: false,
    isFeatured: true,
    retailPrice: null,
    priceOnRequest: true,
    priceTiers: [],
    emoji: '🍓',
    gradient: 'from-red-200 to-pink-100',
  },
  {
    id: 'p-chanh-leo',
    name: 'Chanh leo tím Sơn La',
    slug: 'chanh-leo-tim-son-la',
    categorySlug: 'chanh-leo',
    categoryName: 'Chanh leo',
    unit: 'kg',
    minOrderQuantity: 10,
    shortDescription: 'Chanh leo quả tím đạt chuẩn xuất khẩu châu Âu, độ chua ổn định.',
    description:
      'Chanh leo tím giống Đài Nông 1 đạt GlobalGAP, vỏ dày chịu vận chuyển, dịch quả đạt chuẩn chế biến và xuất tươi sang EU. Cho thu quanh năm, rộ từ tháng 6 đến tháng 11.',
    origin: 'Giống Đài Nông 1',
    growingRegion: 'Mộc Châu, Sơn La',
    harvestPeriod: 'Quanh năm, rộ tháng 6 – 11',
    season: { startMonth: 6, endMonth: 11, peakMonth: 9, label: 'Tháng 6 – 11' },
    certifications: ['GlobalGAP'],
    isExportQuality: true,
    isFeatured: false,
    retailPrice: 25000,
    priceOnRequest: false,
    priceTiers: [
      { minQuantity: 10, price: 25000, label: 'Từ 10kg' },
      { minQuantity: 100, price: 21000, label: 'Từ 100kg' },
      { minQuantity: 500, price: 18000, label: 'Từ 500kg' },
      { minQuantity: 1000, price: 16000, label: 'Từ 1 tấn' },
    ],
    emoji: '🟣',
    gradient: 'from-purple-200 to-violet-100',
  },
  {
    id: 'p-na',
    name: 'Na sầu riêng Mai Sơn',
    slug: 'na-sau-rieng-mai-son',
    categorySlug: 'na',
    categoryName: 'Na',
    unit: 'kg',
    minOrderQuantity: 10,
    shortDescription: 'Quả 0,7–1,5kg, thịt dai ngọt thanh, hàng tuyển biếu tặng và siêu thị.',
    description:
      'Na sầu riêng (na Thái ghép) quả to 0,7–1,5kg, ít hạt, thịt dai ngọt thanh. Phân khúc cao cấp cho siêu thị và giỏ quà biếu. Sản lượng giới hạn — giá báo theo tuần.',
    origin: 'Na sầu riêng (na Thái ghép)',
    growingRegion: 'Mai Sơn, Sơn La',
    harvestPeriod: 'Tháng 8 – 11',
    season: { startMonth: 8, endMonth: 11, peakMonth: 9, label: 'Tháng 8 – 11' },
    certifications: ['VietGAP'],
    isExportQuality: false,
    isFeatured: true,
    retailPrice: null,
    priceOnRequest: true,
    priceTiers: [],
    emoji: '🍈',
    gradient: 'from-emerald-200 to-green-100',
  },
];

export const MOCK_CATEGORIES: Category[] = [
  { name: 'Xoài', slug: 'xoai', productCount: 2 },
  { name: 'Nhãn', slug: 'nhan', productCount: 1 },
  { name: 'Mận', slug: 'man', productCount: 1 },
  { name: 'Dâu tây', slug: 'dau-tay', productCount: 1 },
  { name: 'Chanh leo', slug: 'chanh-leo', productCount: 1 },
  { name: 'Na', slug: 'na', productCount: 1 },
];

export const MOCK_REGIONS = ['Yên Châu', 'Mộc Châu', 'Sông Mã', 'Mai Sơn'];

export const MOCK_POSTS: Post[] = [
  {
    title: 'Lịch mùa vụ trái cây Sơn La 2026: tháng nào có gì?',
    slug: 'lich-mua-vu-trai-cay-son-la-2026',
    excerpt:
      'Tổng hợp lịch thu hoạch xoài, nhãn, mận hậu, na, dâu tây... tại Sơn La để các đại lý chủ động kế hoạch nhập hàng.',
    category: 'mua-vu',
    categoryLabel: 'Mùa vụ',
    publishedAt: '2026-06-01',
  },
  {
    title: 'Quy trình xuất khẩu xoài Yên Châu sang Trung Quốc chính ngạch',
    slug: 'quy-trinh-xuat-khau-xoai-yen-chau',
    excerpt:
      'Mã số vùng trồng, kiểm dịch thực vật, quy cách đóng thùng và những lưu ý khi xuất khẩu chính ngạch.',
    category: 'xuat-khau',
    categoryLabel: 'Xuất khẩu',
    publishedAt: '2026-05-20',
  },
  {
    title: 'Giá nhãn Sông Mã đầu vụ: nhận định thị trường tháng 7',
    slug: 'gia-nhan-song-ma-dau-vu',
    excerpt: 'Phân tích cung cầu và dự báo giá nhãn sỉ tại vườn cho thương lái, chợ đầu mối.',
    category: 'gia-thi-truong',
    categoryLabel: 'Giá thị trường',
    publishedAt: '2026-05-10',
  },
];

export const MOCK_REVIEWS: Review[] = [
  {
    authorName: 'Anh Hùng',
    companyName: 'Vựa trái cây chợ Long Biên',
    content:
      'Hàng đều, đóng sọt chắc chắn, xe về đúng giờ hẹn 4h sáng. Làm với vườn 3 vụ xoài rồi.',
    rating: 5,
  },
  {
    authorName: 'Chị Lan',
    companyName: 'Chuỗi cửa hàng Fruit House',
    content:
      'Nhãn Sông Mã cùi dày, khách phản hồi tốt. Có chứng từ VietGAP đầy đủ để vào siêu thị.',
    rating: 5,
  },
  {
    authorName: 'Mr. Chen',
    companyName: 'Công ty XNK Hoa Quả Việt-Trung',
    content: 'Đóng container chuẩn kiểm dịch, mã vùng trồng rõ ràng, thông quan thuận lợi.',
    rating: 5,
  },
];

export const SITE = {
  name: 'Nhà Vườn Sơn La',
  tagline: 'Trái cây sỉ từ cao nguyên Sơn La',
  hotline: '0888 000 999',
  email: 'kinhdoanh@nhavuonsonla.vn',
  zalo: 'https://zalo.me/0888000999',
  facebook: 'https://facebook.com/nhavuonsonla',
  address: 'Bản Áng, Đông Sang, Mộc Châu, Sơn La',
};
